I don't know what's up with Brefcom, but I need yade to compile, because those guys who will sell us 16-core machine will be using this SVN revision for their benchmarks.
This commit fixes following error:

NameError: name 'brefcomInclude' is not defined:
File "/home/janek/20-Programowanie/10-cpp/50-Yade/Code/CURRENT-Gael/SConstruct", line 453:
env.SConscript(dirs=['.'],build_dir=buildDir,duplicate=0)
File "/home/janek/20-Programowanie/10-cpp/50-Yade/Code/CURRENT-Gael/scons-local/scons-local-0.97.0d20071212/SCons/Script/SConscript.py", line 533:
return apply(_SConscript, [self.fs,] + files, subst_kw)
	File "/home/janek/20-Programowanie/10-cpp/50-Yade/Code/CURRENT-Gael/scons-local/scons-local-0.97.0d20071212/SCons/Script/SConscript.py", line 256:
	exec _file_ in call_stack[-1].globals
	File "/home/janek/20-Programowanie/10-cpp/50-Yade/Code/CURRENT-Gael/SConscript", line 2:
	SConscript(dirs=env['yadeModules'])
	File "/home/janek/20-Programowanie/10-cpp/50-Yade/Code/CURRENT-Gael/scons-local/scons-local-0.97.0d20071212/SCons/Script/SConscript.py", line 596:
return apply(method, args, kw)
	File "/home/janek/20-Programowanie/10-cpp/50-Yade/Code/CURRENT-Gael/scons-local/scons-local-0.97.0d20071212/SCons/Script/SConscript.py", line 533:
return apply(_SConscript, [self.fs,] + files, subst_kw)
	File "/home/janek/20-Programowanie/10-cpp/50-Yade/Code/CURRENT-Gael/scons-local/scons-local-0.97.0d20071212/SCons/Script/SConscript.py", line 256:
	exec _file_ in call_stack[-1].globals
	File "/home/janek/20-Programowanie/10-cpp/50-Yade/Code/CURRENT-Gael/extra/SConscript", line 51:
	LIBS=env['LIBS']+['Shop','Clump']),